login:
    path:     /login
    defaults: { _controller: TodoSecurityBundle:Security:login }
    methods:  [GET]

login_check:
    path:     /login_check
    methods:  [POST]

logout:
    path:     /logout
    methods:  [GET]

logout_validator:
    path: /logoutvalidator
    defaults: { _controller: TodoSecurityBundle:Security:logoutValidator }
    methods:  [GET]